send_sms:
  fields:
    number:
      required: true
      example: "07700 900123"
      selector:
        text:
          type: tel
    message:
      required: true
      example: "Gates opening"
      selector:
        text:
          multiline: true
